### ISSUE TITLE
Démarrer une nouvelle application Angular et la mettre en place sous netlify

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-front-p2020#1]
Objectif démarrer une nouvelle application qu'on va appeler "burgers" et la publier sur netflify.

# Démarrer l'app 
Pour démarrer une application angular:
https://angular.io/guide/setup-local

Ceci va vous permettre de créer une application Angular à partir de Zéro

```
Important: angular 9.1 est sorti, donc pour ceux qui démarrent le projet de 0, ils peuvent partir en 9.1.
Pour ceux qui ont déja le projet et qu'il est en 8, il peuvent rester en 8
```

Pour la suite des travaux, on se référera au[ tuto d'angular: tour of heroes](https://angular.io/tutorial) qui est très bien fait et permet de monter en compétences.

# déployer sous netlify
Mettre en place l'intégration continue ainsi que le déploiement continu via netflify https://www.netlify.com/

La doc qui va bien: https://www.netlify.com/blog/2019/09/23/first-steps-using-netlify-angular/

A l'issue de ce travail vous devez avec une application vierge, mais déployée sous netlify et avec le code sous github. 
On s'était arrêté à ce niveau avant de se quitter, donc il s'agit simplement que tout le monde soit au même niveau

Poster ici votre le lien vers le repository et votre app sous netlify

**Comment by Fantome071** [comment]
Debuigny Léo : 
https://github.com/Fantome071/angular_01
https://angular-ghost.netlify.app/

**Comment by Manouuu** [comment]
LACROIX Emmanuel
https://github.com/Manouuu/LPA2-Front
https://determined-poincare-a83b16.netlify.app/

**Comment by Gyskard** [comment]
MARGUERITAT Thomas
https://github.com/Gyskard/angular-burger
https://dazzling-mirzakhani-cbe865.netlify.app/

**Comment by AntoineMURE** [comment]
MURÉ Antoine
https://github.com/AntoineMURE/Angular
https://silly-hypatia-7add97.netlify.app/

**Comment by zaturgo** [comment]
BLANCHARD Hugo
https://github.com/zaturgo/LPA2-Angular-2020
https://wizardly-poitras-818bf6.netlify.app

**Comment by AlixCoat** [comment]
COATLEVEN Alix
https://github.com/AlixCoat/front2020
https://sad-mestorf-6b6d2a.netlify.app/

**Comment by Quent1nl** [comment]
LAM Quentin 
https://github.com/Quent1nl/Lpang
https://stupefied-euler-90deb3.netlify.app

**Comment by youbensahra** [comment]
BEN SAHRA Youssef
https://github.com/youbensahra/angular
https://bensahra-angular.netlify.app/

**Comment by ChloeViei** [comment]
VIEILLE Chloé
https://github.com/ChloeViei/test_application_angular
https://testapplicationangular.netlify.app/

**Comment by nicolas-fremondiere** [comment]
Fremondiere Nicolas
https://burger4ever.netlify.app/
https://github.com/nicolas-fremondiere/lpa2_ang

**Comment by m-cabezas** [comment]
CABEZAS Mathias
https://github.com/m-cabezas/LPA2_FRONT.git
https://burgerlpa2.netlify.app/

**Comment by HugoL90** [comment]
LAURENT Hugo
https://github.com/HugoL90/AngularProjectBurger
https://lucid-shockley-e85369.netlify.app/

**Comment by MatraneBadr** [comment]
Matrane badr
https://github.com/MatraneBadr/Angular
https://agitated-lamport-2de4b6.netlify.app/

**Comment by leabrnr** [comment]
BRUNORI Léa
https://github.com/leabrnr/angular
https://burger-lb216.netlify.app/

**Comment by SamuelPelsy** [comment]
PELSY-MOZIMANN Samuel
https://github.com/SamuelPelsy/angluar
https://spelsy-angular-app.netlify.app/

**Comment by thoKling** [comment]
KLING Thomas
https://github.com/thoKling/Burgers_front/tree/master
https://stupefied-gates-ec5b30.netlify.app/

**Comment by mael-brdn** [comment]
Bourdon Maël
https://github.com/mael-brdn/lpa2-angular
https://lpa2-angular.netlify.app/

**Comment by alexis-dtrvl** [comment]
DAUTREVILLE Alexis
https://github.com/alexis-dtrvl/lpa2_front_project
https://burger-angular.netlify.app

**Comment by AlexandreDHE** [comment]
DELAHOUSSE Alexandre
https://github.com/AlexandreDHE/UTBM-2019-WEB_Burgers_app_2
https://zen-liskov-097a7e.netlify.app/

**Comment by lripoche** [comment]
Ripoche Lucas
https://github.com/lripoche/LP71-front
https://keen-kare-b09b23.netlify.app

**Comment by Styyg** [comment]
HIRTH Matthieu
https://github.com/Stygma7/angular
https://styg-burgers.netlify.app/

**Comment by AdrienFoucaultUTBM** [comment]
FOUCAULT Adrien
https://github.com/AdrienFoucaultUTBM/lpa2-angular-burger
https://fervent-banach-dada75.netlify.app/

**Comment by glechant** [comment]
Guillaume Lechantre
https://loving-meninsky-f628ff.netlify.app/
https://github.com/glechant/lpa2-angular

**Comment by dmusy** [comment]
MUSY Damien
https://keen-benz-40fb7f.netlify.app/
https://github.com/dmusy/lpa2-angular

**Comment by HassanBzd** [comment]
BOUZID Hassan
https://github.com/HassanBzd/LPA2ProjectFront
https://determined-shockley-c15266.netlify.app/

**Comment by KillianMrg** [comment]
MORGE Killian
https://optimistic-pike-55e89a.netlify.app/
https://github.com/KillianMrg/Burger-Angular-Front

**Comment by flamerant** [comment]
LAMERANT Félicie
https://github.com/flamerant/lpa2-back-P2020
https://lesburgersdefeloche.netlify.app/

**Comment by LPA2-Automne2016** [comment]
OK
