### ISSUE TITLE
Extraire le client burger depuis swagger

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-front-p2020#2]
# Objectif
Comprendre ce qu'est une définition d'API au travers de swagger
Intégrer le client auto généré par Swagger dans l'application angular
Utiliser ce client pour récupérer la liste des burgers
Réaliser son premier template dans angular pour afficher la liste avec le nom des burgers

# Commencer par s'orienter dans l'architecture angular
Commencez par lire le tuto angular en entier, pour avoir une vue d'ensemble, pas besoin de comprendre le moindre détail, ca viendra apres.   https://angular.io/tutorial

# Swagger
Commencez par comprendre ce que fait swagger: https://swagger.io/solutions/api-design/
Il documente vos API et vous permet de les mocker ( il déploie un serveur qui sert les exemples donnés dans le fichier de documentation, pratique pour gagner du temps quand on développe)

Notre API commune est disponible ici: https://app.swaggerhub.com/apis/LPA2-Automne2016/burger/1.0-oas3 prenez en connaissance

# Intégrer les services générés par swagger dans angular:
* Téléchargez le code client depuis [la page de notre spec](https://app.swaggerhub.com/apis/LPA2-Automne2016/burger/1.0-oas3) : Export > client SDK > typescipt-angular
* extraire les classes fournies dans votre arborescence angular (faites un sous dossier pour les ranger)
* installer rxjs-compat  `npm i rxjs-compat --save`
* importer Apimodule et HttpClientModule dans votre fichier app.module.ts
```typescript
@NgModule({
  imports: [
    ApiModule,
   HttpClientModule 
  ],
    providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Voila vous venez de créer votre premier service angular, vous pouvez maintenant l'utiliser dans vos composants ! ( cf la doc comment se le faire injecter dans un composant : https://angular.io/tutorial/toh-pt4#inject-the-heroservice)

# Afficher la liste de nos burgers
Maintenant qu'on a accès à une liste de burgers via notre service ( ou plutot à un Observable de Burgers ) cf la doc ici : https://angular.io/tutorial/toh-pt4#observable-heroservice Il ne reste plus qu'à l'afficher ! ( cf la partie dédiée dans la doc: https://angular.io/tutorial/toh-pt2 )

# Bilan
On a fait appel à une API distante ( qu'on a d'ailleurs pas écrite pour de vrai ) en utilsant un code client qu'on a pas écrit non plus... ( elle est pas belle la vie ? ), mais qui nous retourne de vraies fausses données ! Et on a affiché ces données dans une jolie liste.

Le CSS et l'affichage viendront plus tard, on utilisera une bibliothèque dédiée pour cela.

# A rendre:
L'url vers votre code
L'url vers votre appli en ligne

**Comment by Fantome071** [comment]
Debuigny Léo : 
https://github.com/Fantome071/angular_01
https://angular-ghost.netlify.app/

**Comment by thoKling** [comment]
KLING Thomas
https://github.com/thoKling/Burgers_front/tree/master
https://stupefied-gates-ec5b30.netlify.app/

**Comment by MatraneBadr** [comment]
Matrane badr
https://github.com/MatraneBadr/Angular
https://agitated-lamport-2de4b6.netlify.app/

**Comment by lripoche** [comment]
Ripoche Lucas 
https://github.com/lripoche/LP71-front
https://keen-kare-b09b23.netlify.app

**Comment by AlexandreDHE** [comment]
Alexandre Delahousse
https://zen-liskov-097a7e.netlify.app/
https://github.com/AlexandreDHE/UTBM-2019-WEB_Burgers_app_2

**Comment by glechant** [comment]
Guillaume Lechantre
https://loving-meninsky-f628ff.netlify.app/
https://github.com/glechant/lpa2-angular

**Comment by AntoineMURE** [comment]
MURÉ Antoine
https://github.com/AntoineMURE/Angular
https://silly-hypatia-7add97.netlify.app/

**Comment by AlixCoat** [comment]
COATLEVEN Alix
https://github.com/AlixCoat/front2020
https://sad-mestorf-6b6d2a.netlify.app/

**Comment by Manouuu** [comment]
LACROIX Emmanuel
https://github.com/Manouuu/LPA2-Front
https://determined-poincare-a83b16.netlify.app/

**Comment by Quent1nl** [comment]
LAM Quentin 
https://github.com/Quent1nl/Lpang
https://stupefied-euler-90deb3.netlify.app

**Comment by SamuelPelsy** [comment]
PELSY-MOZIMANN Samuel
https://github.com/SamuelPelsy/angluar
https://spelsy-angular-app.netlify.app/

**Comment by Styyg** [comment]
HIRTH Matthieu
https://github.com/Stygma7/angular
https://styg-burgers.netlify.app

**Comment by dmusy** [comment]
MUSY Damien
https://github.com/dmusy/lpa2-angular
https://keen-benz-40fb7f.netlify.app/

**Comment by nicolas-fremondiere** [comment]
Fremondiere Nicolas
https://burger4ever.netlify.app/
https://github.com/nicolas-fremondiere/lpa2_ang

**Comment by HugoL90** [comment]
Hugo LAURENT
https://lucid-shockley-e85369.netlify.app/
https://github.com/HugoL90/AngularProjectBurger

**Comment by ChloeViei** [comment]
Vieille Chloé 
https://github.com/ChloeViei/test_application_angular
https://testapplicationangular.netlify.app/

**Comment by Gyskard** [comment]
Thomas Margueritat
https://github.com/Gyskard/angularburger
https://dazzling-pike-c86d0e.netlify.app/

**Comment by alexis-dtrvl** [comment]
DAUTREVILLE Alexis
https://github.com/alexis-dtrvl/lpa2_front_project
https://burger-angular.netlify.app/

**Comment by youbensahra** [comment]
https://github.com/youbensahra/angular
https://bensahra-angular.netlify.app/

**Comment by AdrienFoucaultUTBM** [comment]
FOUCAULT Adrien
https://github.com/AdrienFoucaultUTBM/lpa2-angular-burger
https://affectionate-golick-a29bc8.netlify.app/

**Comment by m-cabezas** [comment]
CABEZAS Mathias
https://github.com/m-cabezas/LPA2_FRONT
https://burgerlpa2.netlify.app/

**Comment by zaturgo** [comment]
BLANCHARD Hugo
https://github.com/zaturgo/LPA2-Angular-2020
https://wizardly-poitras-818bf6.netlify.app/

**Comment by mael-brdn** [comment]
BOURDON Maël
https://github.com/mael-brdn/lpa2-angular
https://lpa2-angular.netlify.app/

**Comment by Duresapz** [comment]
PAJAZITI Duresa
https://github.com/Duresapz/Burgers
https://angry-davinci-d5db0d.netlify.app/

**Comment by leabrnr** [comment]
BRUNORI Léa
https://github.com/leabrnr/angular
https://burger-lb216.netlify.app/

**Comment by HassanBzd** [comment]
https://github.com/HassanBzd/LPA2ProjectFront
https://determined-shockley-c15266.netlify.app

**Comment by KillianMrg** [comment]
MORGE Killian
https://optimistic-pike-55e89a.netlify.app/
https://github.com/KillianMrg/Burger-Angular-Front

**Comment by flamerant** [comment]
LAMERANT Félicie
https://github.com/flamerant/LPA2-2020-Angular
https://lesburgersdefel.netlify.app

**Comment by mamieve15** [comment]
BA Awa
https://github.com/mamieve15/burger
https://awaba.netlify.app
