### ISSUE TITLE
Mise en place css material et navigation

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-front-p2020#3]
# Objectif

1. Mettre en place la librairie de composants angular material pour bénéficier d'une librairie de composants qui intègre un framework CSS
2. Mettre en place le routage dans l'application

# Material
Angular rmaterial est une bibiliothèque de composants déja développés et livrés avec le CSS matérial. Cette bibliothèque permet d'accélérer le développement d'applications en bénéficiant d'éléments prédéveloppés. https://material.angular.io/

Commencer par installer material dans le projet: cf [la doc ](https://material.angular.io/guide/getting-started)

Une fois la librairie installée, modifer votre template de départ pour remplacer la liste à puce par des cartes material: https://material.angular.io/components/card/overview

mettre le nom du burger dans le titre, ainsi que l'image du burger et pour finir le prix dans le texte de la carte, cf les examples: https://material.angular.io/components/card/examples.

**ATTENTION** il faudra importer les modules correspondants à la carte et aux boutons ( cf rubrique API de chaque composant: https://material.angular.io/components/card/api )
example : 

```
import {MatCardModule} from '@angular/material/card'; 
```

L'import est à faire dans le app.module.ts

# Routing
Pour qu'une application angular soit fonctionnelle il faut pouvoir naviguer de page en page. Si on reprend notre exemple, il faudrait que lorsqu'on clique sur le bouton en bas de la carte, on navigue vers la description d'une pizza, avec les détails du nutriscore.

Tout le fonctionnement du routing est décrit en détail ici: https://angular.io/tutorial/toh-pt5
Suivre le tutorial en l'adaptant pour ajouter le lien demandé dans la carte, qui permette d'afficher le détail d'un burger.

Rendre ici le lien vers votre app en ligne et le lien vers le code.

**Comment by Fantome071** [comment]
Debuigny Léo :
https://angular-ghost.netlify.app/
https://github.com/Fantome071/angular_01

**Comment by nicolas-fremondiere** [comment]
Fremondiere Nicolas
https://burger4ever.netlify.app/
https://github.com/nicolas-fremondiere/lpa2_ang

**Comment by HugoL90** [comment]
Hugo LAURENT
https://lucid-shockley-e85369.netlify.app/
https://github.com/HugoL90/AngularProjectBurger

**Comment by dmusy** [comment]
MUSY Damien
https://github.com/dmusy/lpa2-angular
https://keen-benz-40fb7f.netlify.app/

**Comment by MatraneBadr** [comment]
Matrane badr
https://github.com/MatraneBadr/Angular
https://agitated-lamport-2de4b6.netlify.app/

**Comment by SamuelPelsy** [comment]
PELSY-MOZIMANN Samuel

https://github.com/SamuelPelsy/angluar
https://spelsy-angular-app.netlify.app

**Comment by m-cabezas** [comment]
CABEZAS Mathias
https://github.com/m-cabezas/LPA2_FRONT
https://burgerlpa2.netlify.app/

**Comment by AlixCoat** [comment]
COATLEVEN Alix
https://sad-mestorf-6b6d2a.netlify.app
https://github.com/AlixCoat/front2020

**Comment by ChloeViei** [comment]
Vieille Chloé
https://testapplicationangular.netlify.app/
https://github.com/ChloeViei/test_application_angular

**Comment by zaturgo** [comment]
Hugo BLANCHARD
https://github.com/zaturgo/LPA2-Angular-2020
https://wizardly-poitras-818bf6.netlify.app/

**Comment by leabrnr** [comment]
BRUNORI Léa
https://github.com/leabrnr/angular
https://burger-lb216.netlify.app/

**Comment by AntoineMURE** [comment]
MURÉ Antoine
https://github.com/AntoineMURE/Angular
https://silly-hypatia-7add97.netlify.app/

**Comment by AdrienFoucaultUTBM** [comment]
Adrien FOUCAULT
https://github.com/AdrienFoucaultUTBM/lpa2-angular-burger
https://affectionate-golick-a29bc8.netlify.app/

**Comment by Gyskard** [comment]
Thomas Margueritat
https://github.com/Gyskard/angularburger
https://dazzling-pike-c86d0e.netlify.app/

**Comment by Manouuu** [comment]
Emmanuel LACROIX
https://github.com/Manouuu/LPA2-Front
https://determined-poincare-a83b16.netlify.app/

**Comment by Quent1nl** [comment]
Quentin LAM
https://github.com/Quent1nl/Lpang
https://stupefied-euler-90deb3.netlify.app

**Comment by lripoche** [comment]
Lucas RIPOCHE
https://github.com/lripoche/LP71-front
https://keen-kare-b09b23.netlify.app/

**Comment by thoKling** [comment]
KLING Thomas
https://github.com/thoKling/Burgers_front/tree/master
https://stupefied-gates-ec5b30.netlify.app/

**Comment by KillianMrg** [comment]
MORGE Killian 
https://github.com/KillianMrg/Burger-Angular-Front
https://optimistic-pike-55e89a.netlify.app/

**Comment by Duresapz** [comment]
Alexandre Delahousse
https://github.com/AlexandreDHE/UTBM-2019-WEB_Burgers_app_2
https://zen-liskov-097a7e.netlify.app/

**Comment by AlexandreDHE** [comment]
Alexandre Delahousse
https://github.com/AlexandreDHE/UTBM-2019-WEB_Burgers_app_2
https://zen-liskov-097a7e.netlify.app/

**Comment by Duresapz** [comment]
Duresa Pajaziti
https://github.com/Duresapz/Burgers
https://angry-davinci-d5db0d.netlify.app/

**Comment by youbensahra** [comment]
BEN SAHRA Youssef
https://github.com/youbensahra/angular
https://bensahra-angular.netlify.app/

**Comment by flamerant** [comment]
LAMERANT Félicie
https://github.com/flamerant/LPA2-2020-Angular
https://lesburgersdefel.netlify.app

**Comment by alexis-dtrvl** [comment]
DAUTREVILLE Alexis
https://github.com/alexis-dtrvl/lpa2_front_project
https://burger-angular.netlify.app/

**Comment by Styyg** [comment]
HIRTH Matthieu
https://styg-burgers.netlify.app/
https://github.com/Stygma7/angular

**Comment by mael-brdn** [comment]
Maël Bourdon
https://lpa2-angular.netlify.app/
https://github.com/mael-brdn/lpa2-angular

**Comment by mamieve15** [comment]
BA Awa
https://github.com/mamieve15/burger
https://awaba.netlify.app/
